// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// get_cumulant_diffs
arma::mat get_cumulant_diffs(arma::mat W_T, arma::ivec type, int order);
RcppExport SEXP _lvmmrPQL_get_cumulant_diffs(SEXP W_TSEXP, SEXP typeSEXP, SEXP orderSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type W_T(W_TSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type type(typeSEXP);
    Rcpp::traits::input_parameter< int >::type order(orderSEXP);
    rcpp_result_gen = Rcpp::wrap(get_cumulant_diffs(W_T, type, order));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_lvmmrPQL_get_cumulant_diffs", (DL_FUNC) &_lvmmrPQL_get_cumulant_diffs, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_lvmmrPQL(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
