# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_cumulant_diffs <- function(W_T, type, order) {
    .Call(`_lvmmrPQL_get_cumulant_diffs`, W_T, type, order)
}

